java -jar /media/DataVolume1/seeuwo/bin/HadoopLocalExtractAnchor.jar -idurlmap /media/DataVolume1/datasets/trec_web_track/new_webtrack_all_all_id_url_list.txt -schema trec -html_tb webtrack_2009 -url_tb webtrack_2009_text_feature -idfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_hadoop_dataset/2009 -outfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_anchors/2009

java -jar /media/DataVolume1/seeuwo/bin/HadoopLocalExtractAnchor.jar -idurlmap /media/DataVolume1/datasets/trec_web_track/new_webtrack_all_all_id_url_list.txt -schema trec -html_tb webtrack_2010 -url_tb webtrack_2010_text_feature -idfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_hadoop_dataset/2010 -outfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_anchors/2010

java -jar /media/DataVolume1/seeuwo/bin/HadoopLocalExtractAnchor.jar -idurlmap /media/DataVolume1/datasets/trec_web_track/new_webtrack_all_all_id_url_list.txt -schema trec -html_tb webtrack_2011 -url_tb webtrack_2011_text_feature -idfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_hadoop_dataset/2011 -outfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_anchors/2011

java -jar /media/DataVolume1/seeuwo/bin/HadoopLocalExtractAnchor.jar -idurlmap /media/DataVolume1/datasets/trec_web_track/new_webtrack_all_all_id_url_list.txt -schema trec -html_tb webtrack_2012 -url_tb webtrack_2012_text_feature -idfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_hadoop_dataset/2012 -outfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_anchors/2012

java -jar /media/DataVolume1/seeuwo/bin/HadoopLocalExtractAnchorOthers.jar -idurlmap /media/DataVolume1/datasets/trec_web_track/new_webtrack_all_all_id_url_list.txt -html_schema trec -html_tb webtrack_others -url_schema clueweb09 -url_tb webpages -idfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_hadoop_dataset/others -outfolder /home/xiao/workspace/HadoopProject/data/trec_webtrack_anchors/others
